name: Build & Publish Packages

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-publish-core:
    name: "Build & Publish UI Core"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: ./src-uicore
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Build package
        run: npm run build
      - name: Get version
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
      - name: Delete package version
        uses: actions/delete-package-versions@v5
        with:
          package-version-ids: ${{ steps.get_version.outputs.version }}
          package-name: coruscant-uicore
          package-type: npm
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
